export const UPDATED_NUMBER  = 'UPDATED_NUMBER';
export const UPDATED_ADJECTIVE = 'UPDATED_ADJECTIVE';
export const UPDATED_SUBJECT = 'UPDATED_SUBJECT';
export const UPDATED_THING = 'UPDATED_THING';
export const UPDATED_ENDING = 'UPDATED_ENDING';